[package]
name = "cli-template"
version = "0.1.0"
edition = "2018"
license = "WTFPL"
publish = false

[dependencies]
clap = "2.33.3"
solana-clap-utils = "1.6"
solana-cli-config = "1.6"
solana-client = "1.6"
solana-logger = "1.6"
solana-remote-wallet = "1.6"
solana-sdk = "1.6"

[dev-dependencies]
solana-validator = "1.6"

[workspace]
